### ISSUE TITLE
Tutorial: Explaining the code?

### ISSUE THREAD

**Issue by rubyFeedback** [subdigital/tic-tac-toe#2]
Hey there,

Would it be possible to explain the code a bit? Does not have to be a 
long document, but mostly for newcomers to gosu.

Not sure if you have time, and motivation to want to do so, but perhaps
if you one day have, I found this project actually from the gosu-forum;
but I am a gosu newcomer so I have no idea how it works.

**Comment by subdigital** [comment]
Don't really have the motivation for this, but this project is sufficiently small that I think it serves as a good example to study on your own. If you have specific questions I can try to answer them, but keep in mind I haven't looked at this code in 5 years :)
